### ISSUE TITLE
DB design

### ISSUE THREAD

**Issue by ghost** [AT-PHPIntership/toeic-test#1]
![screen shot 2017-03-16 at 2 55 41 pm](https://cloud.githubusercontent.com/assets/16182754/23986933/50fcbb6e-0a59-11e7-93ee-0d939097d452.png)

**Comment by at-dinhnhan** [comment]
![db](https://cloud.githubusercontent.com/assets/26216647/24025868/c4ec3b26-0aef-11e7-800d-a473da504ef1.png)

**Comment by at-dinhnhan** [comment]
![db](https://cloud.githubusercontent.com/assets/26216647/24026770/08f3d012-0af6-11e7-96fa-7efd0d53bcdf.png)

**Comment by at-dinhnhan** [comment]
![db](https://cloud.githubusercontent.com/assets/26216647/24190578/9dc7d1ec-0f1b-11e7-80ef-4adf4d828ce2.png)

**Comment by at-dinhnhan** [comment]
/home/dinh/project_laravel/toeic-test/doc/db.png

**Comment by dinhnhan-dtu** [comment]
![db](https://cloud.githubusercontent.com/assets/26216647/24385722/db64ce1e-1395-11e7-83b9-cd75cb501284.png)
